### ISSUE TITLE
A number of problems

### ISSUE THREAD

**Issue by thebadgateway** [jiangxufeng/v2rayL#1]
1) Tray images are not visible. [IMG](https://i106.fastpic.ru/big/2019/0902/50/df7831d132ca4cac0aa54ec98ba7ab50.png)
2) Need English)
3) Which port does the program use?

**Comment by jiangxufeng** [comment]
1.  The color of the icon is black, so it is similar to the background color
2.  1080

Thank you for your question, I am also considering replacing the icon, and I will further optimize it and think of more cases later.

**Comment by NoOne-hub** [comment]
> 1. 托盘图像不可见。[IMG](https://i106.fastpic.ru/big/2019/0902/50/df7831d132ca4cac0aa54ec98ba7ab50.png)
> 2. 需要英文）
> 3. 该程序使用哪个端口？

试试我这个？https://github.com/NoOne-hub/v2ray_client
