### ISSUE TITLE
安装后报错，无法启动

### ISSUE THREAD

**Issue by thtomatic** [jiangxufeng/v2rayL#10]
[27670] Error loading Python lib '/tmp/_MEIkka3Sp/libpython3.6m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIkka3Sp/libpython3.6m.so.1.0)

系统环境：Deepin GNU/Linux 15.11

**Comment by jiangxufeng** [comment]
此程序的使用的内核为v2ray-linux-64，打包环境为ubuntu18.04 + python 3.6
可能是两个系统的环境不一致导致

**Comment by sunnicholas** [comment]
怎么解决呢？

**Comment by jiangxufeng** [comment]
> 怎么解决呢？
上述报错显示GLIBC_2.25这个库没有找到，可能在你们的环境中GLIBC的版本没有到2.25，可以尝试glibc库。
因为我也没碰到具体的这个问题，所以这种方法也只是可能的一种解决办法

**Comment by blue7wings** [comment]
Deepin下同样的问题

**Comment by thtomatic** [comment]
主要是 还卸载不掉了

**Comment by thtomatic** [comment]
> > 怎么解决呢？
> 
> 上述报错显示GLIBC_2.25这个库没有找到，可能在你们的环境中GLIBC的版本没有到2.25，可以尝试glibc库。
> 因为我也没碰到具体的这个问题，所以这种方法也只是可能的一种解决办法

要不你虚拟机装个deepin15.11试试[滑稽]

**Comment by jiangxufeng** [comment]
卸载的话 只要删除文件夹就好了   我待会加上一个卸载脚本

**Comment by everdom** [comment]
我也碰到了，我也用的deepin系统，确实是glibc版本只到2.24，我尝试自己编译glibc2.25版本，可是无法替代系统的，一替代系统会无法启动！劝各位不要轻易尝试，很危险哈哈

**Comment by jiangxufeng** [comment]
> 我也碰到了，我也用的deepin系统，确实是glibc版本只到2.24，我尝试自己编译glibc2.25版本，可是无法替代系统的，一替代系统会无法启动！劝各位不要轻易尝试，很危险哈哈

因为我现在复习考研，实在没有时间去适配其他系统，如果大家愿意的话，可以尝试在自己的系统下打包一下代码，生成可以执行文件，

打包代码为v2rayL-GUI目录下的所有py文件
我自己的打包命令：
pyinstaller -F v2rayLui.py -p config.py -p sub2conf_api.py -p v2rayL_api.py -p v2rayL_threads.py -i images/logo.ico -n v2rayLui

**Comment by Lu-mo** [comment]
我好了,ubuntu16.04,下载的python3.6.5。进v2rayL-GUI目录,
`Python3 v2rayLui.py`
缺什么模块pip3就完事儿了┗|｀O′|┛ 嗷~~
没有再报glibc版本过低
感谢作者,作者牛逼

**Comment by kamike** [comment]
> > 我也碰到了，我也用的deepin系统，确实是glibc版本只到2.24，我尝试自己编译glibc2.25版本，可是无法替代系统的，一替代系统会无法启动！劝各位不要轻易尝试，很危险哈哈
> 
> 因为我现在复习考研，实在没有时间去适配其他系统，如果大家愿意的话，可以尝试在自己的系统下打包一下代码，生成可以执行文件，
> 
> 打包代码为v2rayL-GUI目录下的所有py文件
> 我自己的打包命令：
> pyinstaller -F v2rayLui.py -p config.py -p sub2conf_api.py -p v2rayL_api.py -p v2rayL_threads.py -i images/logo.ico -n v2rayLui

什么v2rayL-GUI目录，完整目录是多少，我怎么没有啊

**Comment by wrb233** [comment]
> 我好了,ubuntu16.04,下载的python3.6.5。进v2rayL-GUI目录,
> `Python3 v2rayLui.py`
> 缺什么模块pip3就完事儿了┗|｀O′|┛ 嗷~~
> 没有再报glibc版本过低
> 感谢作者,作者牛逼

老哥我按你的骚操作弄得，ubuntu16.04,装了一堆module,python3也装了，但是终端打不开了，每次都得切换

**Comment by FenKuan** [comment]
历时4个多小时。终于弄好了。开心。我的系统是deepin15.11。测试了下。订阅功能能用。google啥的都能上。有空我想写一片教程。关于deepin下安装的教程。给各位大哥带带路。(*^__^*) 嘻嘻……

**Comment by imshunzi** [comment]
> 历时4个多小时。终于弄好了。开心。我的系统是deepin15.11。测试了下。订阅功能能用。google啥的都能上。(_^__^_) 嘻嘻……
请问 如何操作的啊 我这报OSError: Python library not found: libpython3.6mu.so.1.0, libpython3.6m.so, libpython3.6m.so.1.0, libpython3.6.so.1.0

sudo apt-get install python3-dev python-dev 这俩已经安装了，但是还是找不到

**Comment by FuGuiLiu** [comment]
> 历时4个多小时。终于弄好了。开心。我的系统是deepin15.11。测试了下。订阅功能能用。google啥的都能上。(_^__^_) 嘻嘻……

怎么搞，有点懵，大哥
