### ISSUE TITLE
下载内核文件失败

### ISSUE THREAD

**Issue by TomCC7** [jiangxufeng/v2rayL#100]
### 报错信息：

--2019-12-24 21:32:17--  http://h1%3Eserver/
Resolving h1>server (h1>server)... failed: Name or service not known.
wget: unable to resolve host address ‘h1>server’
--2019-12-24 21:32:17--  http://error/
Resolving error (error)... failed: Name or service not known.
wget: unable to resolve host address ‘error’
--2019-12-24 21:32:17--  http://(500)%3C/h1
Resolving (500)< ((500)<)... failed: Name or service not known.
wget: unable to resolve host address ‘(500)<’
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

**Comment by jiangxufeng** [comment]
已修复

**Comment by sola97** [comment]
又不行了
报错信息：
--2020-01-01 03:09:00--  https://development4.baidupan.com/010103bb/2019/11/24/facda1c279d32d879f1ba0ba098fe378.tar?st=Lv1LG8a4MRdqT6sNrQ13SQ&e=1577821340&b=AydebAh6UTUDLwB7AzAGbQkuDDVXeAZ0VGYMcw_c_c&fi=14416724&up=
Resolving development4.baidupan.com (development4.baidupan.com)... 122.226.181.186
Connecting to development4.baidupan.com (development4.baidupan.com)|122.226.181.186|:443... connected.
ERROR: cannot verify development4.baidupan.com's certificate, issued by ‘CN=AlphaSSL CA - SHA256 - G2,O=GlobalSign nv-sa,C=BE’:
  Unable to locally verify the issuer's authority.
To connect to development4.baidupan.com insecurely, use `--no-check-certificate'.
