### ISSUE TITLE
服务未开启，无需断开连接

### ISSUE THREAD

**Issue by edr1412** [jiangxufeng/v2rayL#12]
我就想知道「服务未开启，无需断开连接」是什么意思，连接一直是on一关就提示这个，而且居然还删不了配置，说什么当前配置正在使用无法移除。另外他一直提示font的问题。目前是没连上过QAQ

**Comment by jiangxufeng** [comment]
目前我自己也发现的一个小问题是:
电脑开机后第一次连接时开启systemd服务耗时稍微长一点，但是按钮会立即转化为on。

同时，你这个问题也有可能是程序在启动systemd服务时出错，即v2rayL.service并没有正常启动，但是程序已经将状态标记为了on，就会出现你的这种情况

你可以尝试在终端运行一下sudo systemctl start v2rayL.service 查看是否能正常运行。

谢谢issue，我也会进一步改进一些问题

**Comment by arstum** [comment]
Failed

# systemctl start v2rayL.service
Failed to start v2rayL.service: Unit v2rayL.service not found.

**Comment by jiangxufeng** [comment]
> Failed
> 
> root > systemctl start v2rayL.service
> Failed to start v2rayL.service: Unit v2rayL.service not found.

在运行安装脚本时，会添加v2rayL.service至/etc/systemd/system/目录，你这个问题应该是v2rayL.service没有正确的添加到/etc/systemd/system/目录下
