### ISSUE TITLE
其他系统兼容问题

### ISSUE THREAD

**Issue by jiangxufeng** [jiangxufeng/v2rayL#14]
- 这个程序是在ubuntu18.04上打包的，因此可能在其他的系统上会存在一些问题。
- 由于本人现在天天复习准备考研，真的没时间像以前一样来适配大家的系统了，所以大家可以把代码clone下来，然后在自己系统上进行重新打包。
- 项目依赖已经上传，打包文件为v2rayL-GUI目录下的py文件
- 我自己的打包命令：pyinstaller -F v2rayLui.py -p config.py -p sub2conf_api.py -p v2rayL_api.py -p v2rayL_threads.py -i images/logo.ico -n v2rayLui
- 谢谢各位的issue

**Comment by tcstory** [comment]
遇到错误, 是不是命令写错了.


```
$ pyinstaller -F v2rayLui.py -p config.py -p sub2conf_api.py -p v2rayL_api.py -p v2rayL_threads.py -i images/logo.ico -n v2rayL  
23 INFO: PyInstaller: 3.5
23 INFO: Python: 3.7.4
23 INFO: Platform: Linux-5.2.11-1-MANJARO-x86_64-with-arch-Manjaro-Linux
24 INFO: wrote /home/xxxx/v2rayL/v2rayL.spec
25 INFO: UPX is not available.
Traceback (most recent call last):
  File "/usr/bin/pyinstaller", line 10, in <module>
    sys.exit(run())
  File "/usr/lib/python3.7/site-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/lib/python3.7/site-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "/home/xxxx/v2rayL/v2rayL.spec", line 17, in <module>
    noarchive=False)
  File "/usr/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 190, in __init__
    raise ValueError("script '%s' not found" % script)
ValueError: script '/home/xxxx/v2rayL/v2rayLui.py' not found

```

**Comment by jiangxufeng** [comment]
打包文件是v2rayL-GUI里面的 
所以需要在v2rayL-GUI目录下运行

**Comment by jiangxufeng** [comment]
> 遇到错误, 是不是命令写错了.
> 
> 系统是 gnome manjaro, git 的分支是 [047dde6](https://github.com/jiangxufeng/v2rayL/commit/047dde6aa8b0e75231707a50ee44a2f41368e6b7)
> 
> ```
> $ pyinstaller -F v2rayLui.py -p config.py -p sub2conf_api.py -p v2rayL_api.py -p v2rayL_threads.py -i images/logo.ico -n v2rayL  
> 23 INFO: PyInstaller: 3.5
> 23 INFO: Python: 3.7.4
> 23 INFO: Platform: Linux-5.2.11-1-MANJARO-x86_64-with-arch-Manjaro-Linux
> 24 INFO: wrote /home/xxxx/v2rayL/v2rayL.spec
> 25 INFO: UPX is not available.
> Traceback (most recent call last):
>   File "/usr/bin/pyinstaller", line 10, in <module>
>     sys.exit(run())
>   File "/usr/lib/python3.7/site-packages/PyInstaller/__main__.py", line 111, in run
>     run_build(pyi_config, spec_file, **vars(args))
>   File "/usr/lib/python3.7/site-packages/PyInstaller/__main__.py", line 63, in run_build
>     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
>   File "/usr/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 844, in main
>     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
>   File "/usr/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 791, in build
>     exec(code, spec_namespace)
>   File "/home/xxxx/v2rayL/v2rayL.spec", line 17, in <module>
>     noarchive=False)
>   File "/usr/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 190, in __init__
>     raise ValueError("script '%s' not found" % script)
> ValueError: script '/home/xxxx/v2rayL/v2rayLui.py' not found
> ```

打包文件是v2rayL-GUI里面的 
所以需要在v2rayL-GUI目录下运行

**Comment by tcstory** [comment]
@jiangxufeng 好吧谢了, 我真是瞎了

**Comment by Alkane0050** [comment]
> @jiangxufeng 好吧谢了, 我真是瞎了

请问您在manjaro上编译好了吗?
我这里编译出了点问题,没法用:(
