### ISSUE TITLE
V2ray连接后但无法上网

### ISSUE THREAD

**Issue by pope9pope** [jiangxufeng/v2rayL#147]
为什么已经打开了，连接了开关，日志也显示连接成功，但是仍然无法上网。Vmess链接在另外的windows和手机上均能使用

**Comment by ShenEddie** [comment]
https://www.jianshu.com/p/b122584f8941
这篇文章下面提到更改“[设置] -->[network] -->[network proxy]-->[manual]”，ubuntu亲测有效

**Comment by ShenEddie** [comment]
> 为什么已经打开了，连接了开关，日志也显示连接成功，但是仍然无法上网。Vmess链接在另外的windows和手机上均能使用

https://www.jianshu.com/p/b122584f8941
这篇文章下面提到更改“[设置] -->[network] -->[network proxy]-->[manual]”，ubuntu亲测有效

**Comment by pope9pope** [comment]
请问下在deepin系统是如何设置的，这个v2ray我是装在deepin系统的

**Comment by ShenEddie** [comment]
> 请问下在deepin系统是如何设置的，这个v2ray我是装在deepin系统的

在deepin的 设置--网络--系统代理--手动 看看？

![154549nnhhtpe1n0mmvvgm](https://user-images.githubusercontent.com/37097519/77134180-d93a2700-6aa0-11ea-97c7-295c85e55627.png)

**Comment by pope9pope** [comment]
多谢大佬

**Comment by lyh543** [comment]
问题解决了的话，最好把issue close掉

**Comment by pope9pope** [comment]
谢谢

**Comment by xtyi1997** [comment]
> > > > 为什么已经打开了，连接了开关，日志也显示连接成功，但是仍然无法上网。Vmess链接在另外的windows和手机上均能使用
> > > 
> > > 
> > > https://www.jianshu.com/p/b122584f8941
> > > 这篇文章下面提到更改“[设置] -->[network] -->[network proxy]-->[manual]”，ubuntu亲测有效
> > 
> > 
> > 您好，请问更改成什么？那个文章被删了
> 
> 你好，请参考该文章下面的“具体使用方式”部分
> [https://dora_cmon.gitee.io/posts/b22b8242/](url)
> （请将网址复制到浏览器访问，直接点击可能会跳转GitHub界面）

这篇文章显示404了,还请大佬更新一下

**Comment by TZLhenshuai** [comment]
请问一下，v2ray连上 但是上不了网怎么回事呢？

**Comment by ShenEddie** [comment]
> 请问一下，v2ray连上 但是上不了网怎么回事呢？

如果使用的是linux操作系统的话，开启v2rayL软件之后，还需要手动设置系统的代理，才能使网络流量走v2rayL软件的端口。
ubuntu下位于[Settings] -->[network] -->[network proxy]-->[manual]
![image](https://user-images.githubusercontent.com/37097519/102875684-15127a80-447f-11eb-8f79-2048e8cb797f.png)
不知道是不是这个问题。

**Comment by gzz20020424** [comment]
能不能说说arch里面要怎么配置，我是直接导入订阅网址，然后勾选节点，启动后还是被墙
