### ISSUE TITLE
更新或者添加订阅时会闪退

### ISSUE THREAD

**Issue by Armstrong-Douglas** [jiangxufeng/v2rayL#15]
系统： ubuntu1804
pyhton：3.6.8

脚本安装运行后，将订阅地址粘贴点击更新后，直接闪退。
有咩有log文件啊。

**Comment by jiangxufeng** [comment]
谢谢您的issue，我会查看一下原因的，因为最近在复习考研，所以没法立刻解决问题，会抽时间来解决一下大家的问题的。谢谢～～

**Comment by ZeawinL** [comment]
添加订阅失败

`/bin/sh: 1: notify-send: not found
Traceback (most recent call last):
  File "v2rayL_threads.py", line 81, in run
  File "v2rayL_api.py", line 92, in update
  File "sub2conf_api.py", line 172, in update
  File "sub2conf_api.py", line 44, in b642conf
  File "<string>", line 1, in <module>
NameError: name 'null' is not defined`

**Comment by thesomeexp** [comment]
Debian10.1 区域US,添加订阅/配置闪退
```
Fontconfig error: Cannot load config file from /etc/fonts/fonts.conf
Traceback (most recent call last):
  File "v2rayLui.py", line 258, in get_conf_from_uri
  File "subprocess.py", line 287, in call
  File "subprocess.py", line 729, in __init__
  File "subprocess.py", line 1295, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode characters in position 50-55: ordinal not in range(128)
Aborted
```

**Comment by AoEiuV020** [comment]
同崩溃，有没有其他v2ray-gui客户端推荐？

**Comment by AoEiuV020** [comment]
怎么就close了，解决没？@jiangxufeng

**Comment by jiangxufeng** [comment]
@AoEiuV020 你可以尝试一下安装最新的版本，因为我不知道你们使用的订阅地址是什么，所以也不知道导致闪退的问题到底是哪一个，已经尽力把可以发现的漏洞解决了。
如果最新的版本依然存在这个问题，麻烦可以将问题出现的配置或链接发送一下给我嘛？以便更好的找到问题所在。邮箱：541603466@qq.com

**Comment by AoEiuV020** [comment]
我明天试试看，
话说你这出问题有没有日志什么的啊，
我命令行打开也看不到输出，好歹报错写到stderr就好办了，

jiangxufeng <notifications@github.com> 于 2019年11月16日周六 23:33写道：

**Comment by jiangxufeng** [comment]
@AoEiuV020  日志功能现在还不完善，只是一个简单的，可以记录一些出错日志和操作日志。至于命令行打开的话，如果是程序主线程出现问题是会显示错误的，子线程出现错误的话部分不会回显。
如果你有更好的想法或者优化，欢迎pr！

**Comment by AoEiuV020** [comment]
基本确定是padding问题，
base64字符串的字符数是4的倍数，不足的补等号=，
然后base64经常存在省略等号=的，出问题的订阅就是这样的，你代码里写死了添加两个等号，我猜是你的订阅刚好差两个等号吧？
试了下python的base64解码不支持padding错误的情况，也就是等号数量不对的情况，
我不会Python，如果官方base64库不能解决，可能要考虑换个第三方的base64库，

**Comment by jiangxufeng** [comment]
@AoEiuV020，谢谢提供的原因，我会在后面进行优化的，麻烦了
感谢~

**Comment by AoEiuV020** [comment]
python加两个等号还真能解决base64 padding问题，
python只报错缺等号的情况，不报错等号过多的情况，
我今天试着按这个处理一下提个pr，

Suummmmer <notifications@github.com> 于 2019年11月18日周一 11:56写道：

**Comment by AoEiuV020** [comment]
这样看来出问题的应该是vmss://后面的base64没处理了，

AoEiuV020 <aoeiuv020@gmail.com> 于 2019年11月18日周一 12:36写道：
