### ISSUE TITLE
无开启服务权限

### ISSUE THREAD

**Issue by dobma** [jiangxufeng/v2rayL#16]
能打开软件，但是不能正常链接，因为当前用户无开启service的权限。手工运行 sudo -E /usr/bin/v2rayL/v2rayLui即可正常链接。还有链接成功后，不能自动配置系统代理，希望改进。谢谢。

**Comment by jiangxufeng** [comment]
您好，对于第一个问题，在安装脚本里面设置了运行service的权限的，我不知道您那里具体是出了什么问题；第二个的话，因为最近在复习考研，有时间的话会进一步改进的，谢谢issue～
