### ISSUE TITLE
总是占用1080端口

### ISSUE THREAD

**Issue by Ericliu68** [jiangxufeng/v2rayL#17]
默认设置为1080端口，不开启也显示在占用1080端口，无法释放这个端口
ubuntu18.04

**Comment by jiangxufeng** [comment]
您好，对于该问题我在本机上进行了测试，通过修改django项目的监听本地端口
在开启连接时运行python manage.py runserver 1080 报错
CRITICAL - server - Listen failure: Couldn't listen on 127.0.0.1:1080: [Errno 98] Address already in use.
在关闭连接时正常使用

不知道您那里是什么问题，感谢issue

**Comment by Ericliu68** [comment]
我同时安装了electron-ssr 这个工具，每次重启电脑以后，启动ssr，总是提示1080端口被占用，v2ratl没有设置开机自启。

> 您好，对于该问题我在本机上进行了测试，通过修改django项目的监听本地端口
> 在开启连接时运行python manage.py runserver 1080 报错
> CRITICAL - server - Listen failure: Couldn't listen on 127.0.0.1:1080: [Errno 98] Address already in use.
> 在关闭连接时正常使用
> 
> 不知道您那里是什么问题，感谢issue

我同时安装了electron-ssr 这个工具，每次重启电脑以后，启动ssr，总是提示1080端口被占用，v2ratl没有设置开机自启。

**Comment by jiangxufeng** [comment]
> 我同时安装了electron-ssr 这个工具，每次重启电脑以后，启动ssr，总是提示1080端口被占用，v2rayl没有设置开机自启。

你好，我大概知道原因在哪了，因为在v2.0.3之前，v2rayL开机时会自动连接，退出时连接也不会断开，在后面的版本中添加了退出软件断开连接，但是未删除install.sh中的开机自启动
你可以尝试运行一下 sudo systemctl disable v2rayL.service，将开机自启动关闭，应该就不会有这个问题了。

谢谢你的issue，我将会修改一下install.sh

**Comment by Ericliu68** [comment]
> > 我同时安装了electron-ssr 这个工具，每次重启电脑以后，启动ssr，总是提示1080端口被占用，v2rayl没有设置开机自启。
> 
> 你好，我大概知道原因在哪了，因为在v2.0.3之前，v2rayL开机时会自动连接，退出时连接也不会断开，在后面的版本中添加了退出软件断开连接，但是未删除install.sh中的开机自启动
> 你可以尝试运行一下 sudo systemctl disable v2rayL.service，将开机自启动关闭，应该就不会有这个问题了。
> 
> 谢谢你的issue，我将会修改一下install.sh

感谢，十分感谢，楼主真热心！能在提个建议吗！我在用你的工具的时候要手动设置网络代理，每次都有点不方便！这个可以改成自动吗？
