### ISSUE TITLE
ubuntu 20.04 Failed to enable unit: Unit file v2rayL.service does not exist.

### ISSUE THREAD

**Issue by whattoshow** [jiangxufeng/v2rayL#174]
Failed to enable unit: Unit file v2rayL.service does not exist.
使用脚本安装方法可以解决这个问题

**Comment by novice2194** [comment]
> Failed to enable unit: Unit file v2rayL.service does not exist.
> 使用脚本安装方法可以解决这个问题

不行啊，就是用脚本安装的还是报这个错

**Comment by novice2194** [comment]
> > Failed to enable unit: Unit file v2rayL.service does not exist.
> > 使用脚本安装方法可以解决这个问题
> 
> 不行啊，就是用脚本安装的还是报这个错

OK，用管理员权限就好了
