### ISSUE TITLE
/dev/fd/63: 行 64: /usr/bin/v2rayL/v2rayLui: 没有那个文件或目录

### ISSUE THREAD

**Issue by yunyuyuan** [jiangxufeng/v2rayL#201]
/dev/fd/63: 行 64: /usr/bin/v2rayL/v2rayLui: 没有那个文件或目录
用curl安装的请问该怎么解决？

**Comment by fanweiwen** [comment]
我也是一样的问题

**Comment by MerrickZ** [comment]
一样的问题，没有办法安装。

**Comment by yunyuyuan** [comment]
用QV2ray了，很好用。蓝奏:https://wws.lanzous.com/i9Nc9f1ycqd
