### ISSUE TITLE
Failed to start V2RayL Service

### ISSUE THREAD

**Issue by qpc001** [jiangxufeng/v2rayL#22]
` msi@msi-Yoga-C740  ~  sudo systemctl start v2rayL.service
 msi@msi-Yoga-C740  ~  service v2rayL status              
● v2rayL.service - V2RayL Service
   Loaded: loaded (/etc/systemd/system/v2rayL.service; disabled; vendor preset: 
   Active: failed (Result: signal) since Mon 2019-10-07 01:52:06 CST; 8s ago
  Process: 5943 ExecStart=/usr/bin/v2rayL/v2ray -config /etc/v2rayL/config.json 
 Main PID: 5943 (code=killed, signal=SEGV)

10月 07 01:52:06 msi-Yoga-C740 systemd[1]: v2rayL.service: Service hold-off time
10月 07 01:52:06 msi-Yoga-C740 systemd[1]: v2rayL.service: Scheduled restart job
10月 07 01:52:06 msi-Yoga-C740 systemd[1]: Stopped V2RayL Service.
10月 07 01:52:06 msi-Yoga-C740 systemd[1]: v2rayL.service: Start request repeate
10月 07 01:52:06 msi-Yoga-C740 systemd[1]: v2rayL.service: Failed with result 's
10月 07 01:52:06 msi-Yoga-C740 systemd[1]: Failed to start V2RayL Service.
`

**Comment by jiangxufeng** [comment]
您好，您可以手动运行一下/usr/bin/v2rayL/v2ray -config /etc/v2rayL/config.json看看是有什么问题
