### ISSUE TITLE
希望支持自动ON上次的连接

### ISSUE THREAD

**Issue by mzz2017** [jiangxufeng/v2rayL#27]
在每次启动时都需要手动ON一个连接。
希望记住上次ON的连接，这样软件开机启动就会很方便

**Comment by jiangxufeng** [comment]
你好，这个在早期的版本是支持的，由于考虑到一些场景，就取消了，
在后面更新中会添加一个选项以供不同的用户选择退出软件时是否需要自动关闭连接

感谢issue
