### ISSUE TITLE
安装完成，新增一个已经配置好的地址，打不开开关

### ISSUE THREAD

**Issue by kamike** [jiangxufeng/v2rayL#28]
vmware里面装的ubuntu18.0  python2.7    

![image](https://user-images.githubusercontent.com/3920019/66575462-87fc4200-eba8-11e9-994a-9c0c3994d539.png)

打开开关控制台报错：
Warning: The unit file, source configuration file or drop-ins of v2rayL.service changed on disk. Run 'systemctl daemon-reload' to reload units.

**Comment by AmadeusGhost** [comment]
一样打不开 @jiangxufeng 
系统是Manjaro
systemctl status v2rayL.service：
● v2rayL.service - V2RayL Service
   Loaded: loaded (/etc/systemd/system/v2rayL.service; disabled; vendor preset: disabled)
   Active: failed (Result: signal) 
  Process: 4184 ExecStart=/usr/bin/v2rayL/v2ray -config /etc/v2rayL/config.json (code=killed, signal=SEGV)
 Main PID: 4184 (code=killed, signal=SEGV)
v2rayL.service: Service RestartSec=100ms expired, scheduling restart.
systemd[1]: v2rayL.service: Scheduled restart job, restart counter is at 5.
systemd[1]: Stopped V2RayL Service.
systemd[1]: v2rayL.service: Start request repeated too quickly.
systemd[1]: v2rayL.service: Failed with result 'signal'.
systemd[1]: Failed to start V2RayL Service.
systemd[1]: v2rayL.service: Start request repeated too quickly.
systemd[1]: v2rayL.service: Failed with result 'signal'.
systemd[1]: Failed to start V2RayL Service.

**Comment by jiangxufeng** [comment]
你好，可以尝试手动运行一下sudo systemctl start v2rayL.service看一下电脑报什么错嘛

**Comment by jiangxufeng** [comment]
> vmware里面装的ubuntu18.0 python2.7
> 
> ![image](https://user-images.githubusercontent.com/3920019/66575462-87fc4200-eba8-11e9-994a-9c0c3994d539.png)
> 
> 打开开关控制台报错：
> Warning: The unit file, source configuration file or drop-ins of v2rayL.service changed on disk. Run 'systemctl daemon-reload' to reload units.

你好，你可以尝试运行一下systemctl daemon-reload重新load一下文件

**Comment by Fengyuan-Shi** [comment]
manjaro系统下遇到了同样的问题
v2rayL.service - V2RayL Service命令的结果是这样的：
   ```
Loaded: loaded (/etc/systemd/system/v2rayL.service; disabled; vendor preset: disabled)
   Active: failed (Result: signal) since Mon 2019-10-28 22:29:39 CST; 1s ago
  Process: 7991 ExecStart=/usr/bin/v2rayL/v2ray -config /etc/v2rayL/config.json (code=killed, signal=SEGV)
 Main PID: 7991 (code=killed, signal=SEGV)

Oct 28 22:29:39 sfy-laptop-manjaro systemd[1]: v2rayL.service: Service RestartSec=100ms expired, scheduling restart.
Oct 28 22:29:39 sfy-laptop-manjaro systemd[1]: v2rayL.service: Scheduled restart job, restart counter is at 5.
Oct 28 22:29:39 sfy-laptop-manjaro systemd[1]: Stopped V2RayL Service.
Oct 28 22:29:39 sfy-laptop-manjaro systemd[1]: v2rayL.service: Start request repeated too quickly.
Oct 28 22:29:39 sfy-laptop-manjaro systemd[1]: v2rayL.service: Failed with result 'signal'.
Oct 28 22:29:39 sfy-laptop-manjaro systemd[1]: Failed to start V2RayL Service.
```
sudo systemctl start v2rayL.service运行之后没有任何返回结果
