### ISSUE TITLE
中文解码问题

### ISSUE THREAD

**Issue by liulei92** [jiangxufeng/v2rayL#3]
[http://ww1.sinaimg.cn/large/8afa78b7ly1g6t1dtap3mj2088067q3k.jpg](url)
部分 vmess 的title 解码 可能出了问题

**Comment by jiangxufeng** [comment]
我在使用自己的订阅服务解析测试时，没有出现这种情况，中文可以正常显示。
因为初期只遇见过正常的base64解码，因此没有考虑到你出现的这种情况，将会进一步改进。

谢谢指出问题～

**Comment by liulei92** [comment]
目前关系不大，不影响使用
