### ISSUE TITLE
Automatically change system proxy setting when vpn is connected

### ISSUE THREAD

**Issue by endlessbest** [jiangxufeng/v2rayL#30]
I'm on ubuntu 16.04 with the latest v2rayL, it will be much more appreciated if it can change the system proxy setting when the toggle on connections, and reset proxy setting when toggled off. I have to do this manually with Proxy SwitchyOmega on Chrome, which is a little bit annoying.

**Comment by jiangxufeng** [comment]
You can use the auto switch function of Proxy SwitchyOmega to make it unnecessary to set the proxy manually every time. And in subsequent version updates, I will try to add this feature.
Thank you for your issue

**Comment by endlessbest** [comment]
> You can use the auto switch function of Proxy SwitchyOmega to make it unnecessary to set the proxy manually every time. And in subsequent version updates, I will try to add this feature.
> Thank you for your issue

the auto switch only works when switch rules are manually configured in SwichyOmega, that's what makes me sick. it's glad to see the version update, thx in advance.
