### ISSUE TITLE
下载时会卡主不动

### ISSUE THREAD

**Issue by XU0327** [jiangxufeng/v2rayL#37]
![Annotation 2019-10-27 184118](https://user-images.githubusercontent.com/44918689/67633323-7a092980-f8e9-11e9-8d46-d515da3526ae.jpg)
试了好次，都会出现这样的情况

**Comment by XU0327** [comment]
系统是kali linux 2

**Comment by jiangxufeng** [comment]
你好，文件是放在github上面的，下载时是直接从github拉取，你可以检查一下是否是网络的原因
