### ISSUE TITLE
ubuntu 18.04 安装不成功

### ISSUE THREAD

**Issue by 467057463** [jiangxufeng/v2rayL#40]
使用  
```
$ bash <(curl -s -L http://dl.thinker.ink/install.sh)
```
安装后，可件桌面图标，点击无反应。

```
$ systemctl status v2rayL.service
```
显示如下错误
```
● v2rayL.service - V2RayL Service
   Loaded: loaded (/etc/systemd/system/v2rayL.service; disabled; vendor preset: enabled)
   Active: failed (Result: signal) since Wed 2019-10-30 14:27:08 CST; 14min ago
  Process: 7251 ExecStart=/usr/bin/v2rayL/v2ray -config /etc/v2rayL/config.json (code=killed, signal=SEGV)
 Main PID: 7251 (code=killed, signal=SEGV)

10月 30 14:27:08 m2 systemd[1]: v2rayL.service: Service hold-off time over, scheduling restart.
10月 30 14:27:08 m2 systemd[1]: v2rayL.service: Scheduled restart job, restart counter is at 5.
10月 30 14:27:08 m2 systemd[1]: Stopped V2RayL Service.
10月 30 14:27:08 m2 systemd[1]: v2rayL.service: Start request repeated too quickly.
10月 30 14:27:08 m2 systemd[1]: v2rayL.service: Failed with result 'signal'.
10月 30 14:27:08 m2 systemd[1]: Failed to start V2RayL Service.

```

**Comment by jiangxufeng** [comment]
> 使用
> 
> ```
> $ bash <(curl -s -L http://dl.thinker.ink/install.sh)
> ```
> 
> 安装后，可件桌面图标，点击无反应。
> 
> ```
> $ systemctl status v2rayL.service
> ```
> 
> 显示如下错误
> 
> ```
> ● v2rayL.service - V2RayL Service
>    Loaded: loaded (/etc/systemd/system/v2rayL.service; disabled; vendor preset: enabled)
>    Active: failed (Result: signal) since Wed 2019-10-30 14:27:08 CST; 14min ago
>   Process: 7251 ExecStart=/usr/bin/v2rayL/v2ray -config /etc/v2rayL/config.json (code=killed, signal=SEGV)
>  Main PID: 7251 (code=killed, signal=SEGV)
> 
> 10月 30 14:27:08 m2 systemd[1]: v2rayL.service: Service hold-off time over, scheduling restart.
> 10月 30 14:27:08 m2 systemd[1]: v2rayL.service: Scheduled restart job, restart counter is at 5.
> 10月 30 14:27:08 m2 systemd[1]: Stopped V2RayL Service.
> 10月 30 14:27:08 m2 systemd[1]: v2rayL.service: Start request repeated too quickly.
> 10月 30 14:27:08 m2 systemd[1]: v2rayL.service: Failed with result 'signal'.
> 10月 30 14:27:08 m2 systemd[1]: Failed to start V2RayL Service.
> ```

你好，可以尝试卸载后安装一下最新的版本，最新的版本修复了一些关于service文件的问题（但不确定是同一个[:捂脸哭]）

**Comment by 467057463** [comment]
重新安装后报 
```
Cannot open self /usr/bin/v2rayL/v2rayLui or archive /usr/bin/v2rayL/v2rayLui.pkg
```

**Comment by MikoyChinese** [comment]
重新安装要先卸载残留，和把/etc/v2rayL里面的文件删除了。
