### ISSUE TITLE
大佬，为啥我在deepin上安装完成了，但是打不开呢？

### ISSUE THREAD

**Issue by etotakeo** [jiangxufeng/v2rayL#41]
提示好像是安装完成了，但是点击图标的时候打不开

**Comment by jiangxufeng** [comment]
> 提示好像是安装完成了，但是点击图标的时候打不开

因为时间原因，没有在其他的linux系统测试，提供的应用程序也是在ubuntu18.04+python3.6的环境下打包的，可能与deepin不适配。
可以尝试运行一下/usr/bin/v2rayL/v2rayLui，看一下具体报了什么错
