### ISSUE TITLE
请问使用deepin系统，安装完成后无法打开应该怎么解决

### ISSUE THREAD

**Issue by boker123** [jiangxufeng/v2rayL#43]
使用deepin系统，安装软件以后却无法打开，应该怎么操作

**Comment by jiangxufeng** [comment]
> 使用deepin系统，安装软件以后却无法打开，应该怎么操作

可以运行一下/usr/bin/v2rayL/v2rayLui， 看一下具体报了什么错吗？

**Comment by loooo139** [comment]
[11975] Error loading Python lib '/tmp/_MEIJRUGGO/libpython3.6m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIJRUGGO/libpython3.6m.so.1.0)

**Comment by jiangxufeng** [comment]
> [11975] Error loading Python lib '/tmp/_MEIJRUGGO/libpython3.6m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIJRUGGO/libpython3.6m.so.1.0)

这是python版本不一致导致的问题
可以看一下这里，https://github.com/jiangxufeng/v2rayL/issues/10

你也可以尝试把代码clone到本地，然后进入v2rayL-GUI/目录使用下列命令进行打包一下
pyinstaller -F v2rayLui.py -p config.py -p sub2conf_api.py -p v2rayL_api.py -p v2rayL_threads.py -p utils.py -i images/logo.ico
