### ISSUE TITLE
报了个错误

### ISSUE THREAD

**Issue by Qi-HuT** [jiangxufeng/v2rayL#45]
[4978] Error loading Python lib '/tmp/_MEIAGbNs9/libpython3.6m.so.1.0': dlopen: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIAGbNs9/libpython3.6m.so.1.0)

安装完成后报了这个错误

**Comment by jiangxufeng** [comment]
这是python版本不一致导致的问题
[https://github.com/jiangxufeng/v2rayL/issues/10](url)

**Comment by wrb233** [comment]
> > [4978] Error loading Python lib '/tmp/_MEIAGbNs9/libpython3.6m.so.1.0': dlopen: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIAGbNs9/libpython3.6m.so.1.0)
> > 安装完成后报了这个错误
> 
> 这是python版本不一致导致的问题
> [https://github.com/jiangxufeng/v2rayL/issues/10](url)

需要升级到python3.6版本吗？？？现在是python3.5.2

**Comment by jiangxufeng** [comment]
> > > [4978] Error loading Python lib '/tmp/_MEIAGbNs9/libpython3.6m.so.1.0': dlopen: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIAGbNs9/libpython3.6m.so.1.0)
> > > 安装完成后报了这个错误
> > 
> > 
> > 这是python版本不一致导致的问题
> > [https://github.com/jiangxufeng/v2rayL/issues/10](url)
> 
> 需要升级到python3.6版本吗？？？現在是python3.5.2

因为打包的程序使用的是python3.6，所以会不适配，你可以尝试把代码clone到本地，然后进入v2rayL-GUI/目录使用下列命令进行打包一下
pyinstaller -F v2rayLui.py -p config.py -p sub2conf_api.py -p v2rayL_api.py -p v2rayL_threads.py -p utils.py -i images/logo.ico

**Comment by Qi-HuT** [comment]
那能把版本从3.7改为3.6嘛

**Comment by Qi-HuT** [comment]
> > > > [4978] Error loading Python lib '/tmp/_MEIAGbNs9/libpython3.6m.so.1.0': dlopen: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIAGbNs9/libpython3.6m.so.1.0)
> > > > 安装完成后报了这个错误
> > > 
> > > 
> > > 这是python版本不一致导致的问题
> > > [https://github.com/jiangxufeng/v2rayL/issues/10](url)
> > 
> > 
> > 需要升级到python3.6版本吗？？？現在是python3.5.2
> 
> 因为打包的程序使用的是python3.6，所以会不适配，你可以尝试把代码clone到本地，然后进入v2rayL-GUI/目录使用下列命令进行打包一下
> pyinstaller -F v2rayLui.py -p config.py -p sub2conf_api.py -p v2rayL_api.py -p v2rayL_threads.py -p utils.py -i images/logo.ico

那能把3.7 改为3.6嘛

**Comment by jiangxufeng** [comment]
你可以尝试把代码clone到本地，然后进入v2rayL-GUI/目录使用下列命令进行打包一下 pyinstaller -F v2rayLui.py -p config.py -p sub2conf_api.py -p v2rayL_api.py -p v2rayL_threads.py -p utils.py -i images/logo.ico 这个项目的话Python3.7应该可以跑，需要开个虚拟环境装一下requirements里面的依赖，不需要修改为3.6------------------ 原始邮件 ------------------
发件人: "Qi-HuT"<notifications@github.com>
发送时间: 2019年11月5日(星期二) 晚上7:08
收件人: "jiangxufeng/v2rayL"<v2rayL@noreply.github.com>;
抄送: "jiangxufeng"<jiangxufeng1998@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [jiangxufeng/v2rayL] 报了个错误 (#45)


    
[4978] Error loading Python lib '/tmp/_MEIAGbNs9/libpython3.6m.so.1.0': dlopen: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIAGbNs9/libpython3.6m.so.1.0)
 安装完成后报了这个错误
  
这是python版本不一致导致的问题
 https://github.com/jiangxufeng/v2rayL/issues/10
  
需要升级到python3.6版本吗？？？現在是python3.5.2
  
因为打包的程序使用的是python3.6，所以会不适配，你可以尝试把代码clone到本地，然后进入v2rayL-GUI/目录使用下列命令进行打包一下
 pyinstaller -F v2rayLui.py -p config.py -p sub2conf_api.py -p v2rayL_api.py -p v2rayL_threads.py -p utils.py -i images/logo.ico
  
那能把3.7 改为3.6嘛
 
&mdash;

**Comment by jiangxufeng** [comment]
@Qi-HuT 不用改为3.6，3.7应该可以直接跑这个项目，你也可以尝试把代码clone到本地，然后进入v2rayL-GUI/，开个虚拟环境安装一下requirements里面的依赖，然后Python v2rayLui.py，看一下是否可以正常使用，可以的话使用下列命令进行打包
pyinstaller -F v2rayLui.py -p config.py -p sub2conf_api.py -p v2rayL_api.py -p v2rayL_threads.py -p utils.py -i images/logo.ico

**Comment by Qi-HuT** [comment]
> @Qi-HuT 不用改为3.6，3.7应该可以直接跑这个项目，你也可以尝试把代码clone到本地，然后进入v2rayL-GUI/，开个虚拟环境安装一下requirements里面的依赖，然后Python v2rayLui.py，看一下是否可以正常使用，可以的话使用下列命令进行打包
> pyinstaller -F v2rayLui.py -p config.py -p sub2conf_api.py -p v2rayL_api.py -p v2rayL_threads.py -p utils.py -i images/logo.ico

我搞了个虚拟机  python版本是 3.6.3  安装报错   是必须只能是3.6嘛

**Comment by jiangxufeng** [comment]
> > @Qi-HuT 不用改为3.6，3.7应该可以直接跑这个项目，你也可以尝试把代码clone到本地，然后进入v2rayL-GUI/，开个虚拟环境安装一下requirements里面的依赖，然后Python v2rayLui.py，看一下是否可以正常使用，可以的话使用下列命令进行打包
> > pyinstaller -F v2rayLui.py -p config.py -p sub2conf_api.py -p v2rayL_api.py -p v2rayL_threads.py -p utils.py -i images/logo.ico
> 
> 我搞了个虚拟机 python版本是 3.6.3 安装报错 是必须只能是3.6嘛

不是吧，请问报的是一样的错吗？

**Comment by Qi-HuT** [comment]
> > > @Qi-HuT 不用改为3.6，3.7应该可以直接跑这个项目，你也可以尝试把代码clone到本地，然后进入v2rayL-GUI/，开个虚拟环境安装一下requirements里面的依赖，然后Python v2rayLui.py，看一下是否可以正常使用，可以的话使用下列命令进行打包
> > > pyinstaller -F v2rayLui.py -p config.py -p sub2conf_api.py -p v2rayL_api.py -p v2rayL_threads.py -p utils.py -i images/logo.ico
> > 
> > 
> > 我搞了个虚拟机 python版本是 3.6.3 安装报错 是必须只能是3.6嘛
> 
> 不是吧，请问报的是一样的错吗？

是得一样的错 就是说[22366] Error loading Python lib '/tmp/_MEIJl7ydf/libpython3.6m.so.1.0': dlopen: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIJl7ydf/libpython3.6m.so.1.0)

**Comment by jiangxufeng** [comment]
@Qi-HuT 你看看能不能跑一下代码，谢啦！
然后我这一两天看看能不能彻底解决一下这个问题，多装几个虚拟机来适配一下，调整一下安装脚本

**Comment by Qi-HuT** [comment]
> @Qi-HuT 你看看能不能跑一下代码，谢啦！
> 然后我这一两天看看能不能彻底解决一下这个问题，多装几个虚拟机来适配一下，调整一下安装脚本

嗯嗯好  谢谢哈

**Comment by jiangxufeng** [comment]
麻烦了~ @Qi-HuT

**Comment by Qi-HuT** [comment]
你的是啥虚拟机呀 我的是centos7  然后运行就没有zbar  PyQt5.QtWidgets   这两都报错

**Comment by jiangxufeng** [comment]
> 你的是啥虚拟机呀 我的是centos7 然后运行就没有zbar PyQt5.QtWidgets 这两都报错

我电脑是ubuntu183.04 
zbar需要安装 sudo apt-get install zbar-tools
PyQt5的话，你可以开一个Python虚拟环境，然后pip install -r requirements.txt
requirements.txt在github上有～

**Comment by Qi-HuT** [comment]
尴尬了  centos好像不大容易装  zabar    requirements.txt里的我装了  但就是QtWidgets  这报错    哈哈 你可以装几台centos试试

**Comment by jiangxufeng** [comment]
> centos

恩恩，后面我会好好考虑一下适配其他系统环境的，也谢谢你的建议呀！也麻烦你了～～～

**Comment by Qi-HuT** [comment]
哈哈 辛苦你了 得适配那么多环境

**Comment by Qi-HuT** [comment]
老哥你会不会在centos上配置客户端呀 &nbsp; &nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jiangxufeng"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月5日(星期二) 晚上9:08
收件人:&nbsp;"jiangxufeng/v2rayL"<v2rayL@noreply.github.com&gt;;
抄送:&nbsp;"。"<3423725215@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [jiangxufeng/v2rayL] 报了个错误 (#45)



 
centos
  
恩恩，后面我会好好考虑一下适配其他系统环境的，也谢谢你的建议呀！也麻烦你了～～～

**Comment by jiangxufeng** [comment]
@Qi-HuT 先看看有什么方法可以彻底解决这个问题，要不然一个一个适配的话工作量也很大了
