### ISSUE TITLE
使用中文ss url解析名称出错

### ISSUE THREAD

**Issue by hoshinohikari** [jiangxufeng/v2rayL#48]
使用ss url时，解析出来的别名乱码

**Comment by jiangxufeng** [comment]
> 使用ss url时，解析出来的别名乱码

你好，请问一下乱码是什么格式的呢？urlencode？
我应该已经大概知道问题在哪里了，后续会进行优化修复的

谢谢issue

**Comment by hoshinohikari** [comment]
> > 使用ss url时，解析出来的别名乱码
> 
> 你好，请问一下乱码是什么格式的呢？urlencode？
> 我应该已经大概知道问题在哪里了，后续会进行优化修复的
> 
> 谢谢issue

的确是，好像是没有从url里面解码而是直接copy到名称了
