### ISSUE TITLE
IP地址一直是107.175.xx.xx

### ISSUE THREAD

**Issue by piccjeer** [jiangxufeng/v2rayL#51]
安装的时候出了一点错，v2rayLui这个文件只下了20多M，然后下载不动了，过了一会儿提示安装成功。应用程序里面出现图标，但是打开失败。我从releases里面下载了ZIP包，解压得到68M多的v2rayLui，然后复制到usr/bin/v2rayL替换掉只有20M的文件。再打开程序成功。
  但是，我添加链接和订阅地址，chrome里面测试自己IP都为107.175.xx.xx，显示美国地址，倒是可以访问谷歌，但是速度不快。而且这个IP不是我添加的线路。我也不知道怎么来的，难道是软件里面自带的？？问题是，我无法使用我自己的线路。
还有我关掉程序后，chrome仍然能够访问谷歌，也仍然是那个IP地址。这个程序会常驻后台吗？
求教！

**Comment by MikoyChinese** [comment]
一般来讲，这个软件是监听你的1080端口（socket的默认端口），而你用谷歌的话，一般是装了SwitchyOmega这个插件，如果你测试ip应该用全局连接，而不是auto switch 模式,否则默认是你自己。你既然能访问谷歌了，那代表你成功科学上网了。

而软件的逻辑是这样子的。

Client -> 发起请求 -> SwitchyOmega -> 判断请求符合规则就转发给 Inbound -> Local V2ray-core -> 本地v2ray接受到后将数据通过vmess加密发送给outbound -> 绕过GFW -> Server V2ray-core Inbound -> 原路返回.

这也就是V2ray 里面那么多Inbound and Outbound 的原因啦。更改了Inbound and Outbound的加密协议也就分别对应V2ray, ss, ssr。这就是其中的原理。

所以你真正后台跑的应该是v2ray这个可执行程序，作者是安装到/usr/bin/v2rayL/v2ray这里，只要他是自启动，那么就OK。自启动作者已经写了service，所以默认是自启动的。
关闭方法，`sudo systemctl disable/enable v2rayL`.

执行 `ps aux | grep v2ray` 可以看到相关运行进程。

**Comment by MikoyChinese** [comment]
订阅就是去跑别人的ip呀。提供商提供什么节点，就是跑什么节点。

**Comment by jiangxufeng** [comment]
@piccjeer   ，其他的问题感谢@MikoyChinese 的解答
1. 下载问题。因为下载文件是放在github上的(自己服务器上速度太慢了)，所以有些时候可能会因为网络之类的原因导致下载出错

2 . 对于程序关闭这个问题我补充一下，点击程序关闭按钮时，程序不会直接关闭，而是最小化到系统托盘，一般来说在ubuntu也就是右上角，真正退出程序需要从系统托盘处退出，退出后也将自动关闭v2ray服务
