### ISSUE TITLE
不懂就问

### ISSUE THREAD

**Issue by edPanda** [jiangxufeng/v2rayL#52]
我导入订阅后，检测连接显示无连接，想起来配置文件、规则啥的还没弄，我想问下怎么添加呀

**Comment by jiangxufeng** [comment]
@edPanda ，导入了订阅，程序会根据订阅解析出相对应的配置，当点击连接按钮时，就会根据选中的配置生成配置文件，然后启动v2ray服务。
所以配置文件是会自动生成的，只要是程序适配了的协议设置，如mkcp, ws,  @tcp，都可以生成可以用的配置文件，位置为/etc/v2rayL/config.json

**Comment by edPanda** [comment]
可是我点击连接后，再去点击测延迟，却是service unavailable

jiangxufeng <notifications@github.com<mailto:notifications@github.com>>于2019年11月10日 周日20:52写道：

@edPanda<https://github.com/edPanda> ，导入了订阅，程序会根据订阅解析出相对应的配置，当点击连接按钮时，就会根据选中的配置生成配置文件，然后启动v2ray服务。
所以配置文件是会自动生成的，只要是程序适配了的协议设置，如mkcp, ws, @tcp<https://github.com/tcp>，都可以生成可以用的配置文件，位置为/etc/v2rayL/config.json

**Comment by jiangxufeng** [comment]
@edPanda 测试延时是通过代理来访问google实现的，如果返回service unavailable的话，说明通过代理访问失败，有以下几种情况：
1. 当前使用的配置无效
2. 当前使用的配置协议是程序不支持的或者未考虑到的，因此解析生成的config.json文件无效，代理也会失效

你可以试一下这个配置(免费机场里面的一个)
`vmess://eyd2JzogJzInLCAncHMnOiAn5rSb5p2J55+2QS/ml6DpmZAvV3Mv6KeG6aKRJywgJ2FkZCc6ICd2MC5kbG9sYi5tbCcsICdwb3J0JzogJzQ0MycsICdpZCc6ICc0ZmU2OTljOS1mMmQ1LTRjYmItOWQxNi0zNTQ1M2U3NGM3ZWYnLCAnYWlkJzogJzgnLCAnbmV0JzogJ3dzJywgJ3R5cGUnOiAnbm9uZScsICdob3N0JzogJ3YwLmRsb2xiLm1sJywgJ3BhdGgnOiAnL2ZmMTIzJywgJ3Rscyc6ICd0bHMnfQ==`

**Comment by edPanda** [comment]
嗯嗯 我试下

jiangxufeng <notifications@github.com<mailto:notifications@github.com>>于2019年11月10日 周日23:16写道：

@edPanda<https://github.com/edPanda> 测试延时是通过代理来访问google实现的，如果返回service unavailable的话，说明通过代理访问失败，有以下几种情况：

  1.  当前使用的配置无效
  2.  当前使用的配置协议是程序不支持的或者未考虑到的，因此解析生成的config.json文件无效，代理也会失效

你可以试一下这个配置(免费机场里面的一个)
vmess://eyd2JzogJzInLCAncHMnOiAn5rSb5p2J55+2QS/ml6DpmZAvV3Mv6KeG6aKRJywgJ2FkZCc6ICd2MC5kbG9sYi5tbCcsICdwb3J0JzogJzQ0MycsICdpZCc6ICc0ZmU2OTljOS1mMmQ1LTRjYmItOWQxNi0zNTQ1M2U3NGM3ZWYnLCAnYWlkJzogJzgnLCAnbmV0JzogJ3dzJywgJ3R5cGUnOiAnbm9uZScsICdob3N0JzogJ3YwLmRsb2xiLm1sJywgJ3BhdGgnOiAnL2ZmMTIzJywgJ3Rscyc6ICd0bHMnfQ==

**Comment by edPanda** [comment]
嗯嗯。果然可以的。只是我的订阅不可以。谢谢你了！

Panda ed <y1433011488@outlook.com<mailto:y1433011488@outlook.com>>于2019年11月11日 周一18:04写道：

嗯嗯 我试下

jiangxufeng <notifications@github.com<mailto:notifications@github.com>>于2019年11月10日 周日23:16写道：

@edPanda<https://github.com/edPanda> 测试延时是通过代理来访问google实现的，如果返回service unavailable的话，说明通过代理访问失败，有以下几种情况：

  1.  当前使用的配置无效
  2.  当前使用的配置协议是程序不支持的或者未考虑到的，因此解析生成的config.json文件无效，代理也会失效

你可以试一下这个配置(免费机场里面的一个)
vmess://eyd2JzogJzInLCAncHMnOiAn5rSb5p2J55+2QS/ml6DpmZAvV3Mv6KeG6aKRJywgJ2FkZCc6ICd2MC5kbG9sYi5tbCcsICdwb3J0JzogJzQ0MycsICdpZCc6ICc0ZmU2OTljOS1mMmQ1LTRjYmItOWQxNi0zNTQ1M2U3NGM3ZWYnLCAnYWlkJzogJzgnLCAnbmV0JzogJ3dzJywgJ3R5cGUnOiAnbm9uZScsICdob3N0JzogJ3YwLmRsb2xiLm1sJywgJ3BhdGgnOiAnL2ZmMTIzJywgJ3Rscyc6ICd0bHMnfQ==
