### ISSUE TITLE
ws订阅目录识别问题

### ISSUE THREAD

**Issue by ivyshow** [jiangxufeng/v2rayL#54]
{"add":"xxx","host":"xxx","id":"xxx","net":"ws","path":"\\/","port":"8443","ps":"xxx","tls":"tls","v":2,"aid":2,"type":"none"}

这是我的订阅解码，path配置里已经有一个"\\"符号
在shadowrocket,v2rayN/NG,kitsunebi,还有mac的v2rayU之类的都可以正确识别

大佬的版本导入后无法连接，检查config文件发现是path设置有2个"\\"符号

手动修改后用内核直接启动就好了

**Comment by jiangxufeng** [comment]
你好，这个问题应该是将str解析成dict的时候出现的问题，后面会修正

感谢issue
