### ISSUE TITLE
存在 闪退后，无法打开的现象

### ISSUE THREAD

**Issue by liulei92** [jiangxufeng/v2rayL#6]
使用环境：ubuntu 16.04

添加vmess
vmess://eyJhZGQiOiI0Ny4yNDQuNDcuNzUiLCJhaWQiOiIzMiIsImhvc3QiOiIiLCJpZCI6IjgyOTViMDI0LWM1NDQtMTFlOS1iZTQ1LTAwMTYzZTA0MTU5MyIsIm5ldCI6ImtjcCIsInBhdGgiOiIiLCJwb3J0Ijo1MDEyNCwicHMiOiJTU1JUT09MLkNPTSIsInRscyI6Im5vbmUiLCJ0eXBlIjoiZHRscyIsInYiOiIyIn0== 后，存在客户端闪退无法重启现象

**Comment by liulei92** [comment]
按道理，这个vmess 是可以用的，就是不知道是啥原因 导致 添加后就闪退了，现在这个我没添加了

**Comment by liulei92** [comment]
还有 恢复（show） 这个功能 没有效果，不知道是 环境 导致的吗

**Comment by jiangxufeng** [comment]
1.  第一个问题的原因应该是你这个配置解析后，port是int，代码中没有考虑严谨，已修复
2.  恢复的话，我们关闭了客户端界面，缩小到了系统托盘才会弹出，如果只是最小化，因为界面还在，所以不会有消息弹出。不知道你是什么问题

**Comment by liulei92** [comment]
2.我的应该是 窗体还在，只是 最小化了，我也不太会描述我的这一现象。。。
