### ISSUE TITLE
感谢，可以考虑一下添加PAC模式/全局代理的功能吗

### ISSUE THREAD

**Issue by 7578lgg** [jiangxufeng/v2rayL#61]
没有PAC模式还是不够舒服呀，大家怎么解决的

**Comment by jiangxufeng** [comment]
这个目前还是通过Proxy SwitchyOmega插件的auto switch来实现的

**Comment by 0GGmr0** [comment]
https://github.com/mzz2017/V2RayA
我朋友推荐了这款，正在用

**Comment by jiangxufeng** [comment]
最新版已经添加全局透明代理模式(Beta)，目前可能依然存在一些问题，关闭透明代理时不影响以前正常使用
