### ISSUE TITLE
开启代理后还是无法上google

### ISSUE THREAD

**Issue by TheSlientnight** [jiangxufeng/v2rayL#63]
开启代理后还是本机ip，系统deepin15.11

**Comment by TheSlientnight** [comment]
上述问题通过本地打包已解决，但是配置好服务器之后点击链接却没有反应，不知道是否有生效

**Comment by TheSlientnight** [comment]
上述问题已通过本地打包替换解决，但是现在链接服务器后还是无法实现翻墙
![image](https://user-images.githubusercontent.com/37974664/69313773-73ae6900-0c6d-11ea-8eed-521237dd6964.png)

**Comment by jiangxufeng** [comment]
代理开启后，还需配合插件（如：Proxy SwitchyOmega）进行设置，目前程序还不是全局代理

**Comment by jiangxufeng** [comment]
@TheSlientnight 你也可以看一下这个issue里面的回复，[#51](https://github.com/jiangxufeng/v2rayL/issues/51)

**Comment by TheSlientnight** [comment]
> @TheSlientnight 你也可以看一下这个issue里面的回复，[#51](https://github.com/jiangxufeng/v2rayL/issues/51)

感谢~

**Comment by QingYingZero** [comment]
我现在是 v2ray+google 访问助手用的
