### ISSUE TITLE
订阅配置被删除

### ISSUE THREAD

**Issue by xgdgsc** [jiangxufeng/v2rayL#66]
订阅更新失败一次之后，订阅直接被删除，得重新添加

**Comment by jiangxufeng** [comment]
你好，这个问题当时设计的时候没有充分考虑到因为某些原因订阅地址暂时访问失败，所以当更新失败时就会被当做无效地址删除。
后面会优化这个部分的问题的，谢谢issue

**Comment by jiangxufeng** [comment]
已优化
