### ISSUE TITLE
不支持https的订阅链接吗

### ISSUE THREAD

**Issue by handbye** [jiangxufeng/v2rayL#68]
增加https订阅链接提示：无法获取订阅信息，订阅站点访问失败。
我确定订阅连接是可以正常访问的。

**Comment by jiangxufeng** [comment]
你好，https是支持的，可能是因为网络原因之类的导致请求失败

**Comment by jiangxufeng** [comment]
也有一种可能是，开了透明代理导致访问失败

**Comment by handbye** [comment]
> 也有一种可能是，透明代理出现问题，然后开了透明代理导致访问失败，

你好，请问下，怎么关闭透明代理呢，我关了试下

**Comment by jiangxufeng** [comment]
透明代理设置在系统托盘菜单处

**Comment by jiangxufeng** [comment]
因为我自己的订阅也是https的，所以是肯定ok的，原因应该就是requests访问时出现错误

**Comment by handbye** [comment]
> 透明代理设置在系统托盘菜单处

是全局代理吗，我已经把全局代理关闭了，还是不能添加订阅。

**Comment by handbye** [comment]
刚才手动添加了一个ss地址测试了下，开启后就会闪退。 我的版本是V2.1.3,  ubuntu18.04,python3.6
我使用的是你网站的那个一键安装脚本安装的。

**Comment by jiangxufeng** [comment]
你好，可以加一下QQ嘛，可以更好的交流
QQ：541603466

**Comment by jiangxufeng** [comment]
SS的错误我这边也发现了，马上会进行一下修复

**Comment by handbye** [comment]
好的，你修复完，我升级下再试试。我已加你qq,

**Comment by jiangxufeng** [comment]
不好意思，没有收到你的申请诶，
ss的问题已经找到，马上会进行修复

**Comment by jiangxufeng** [comment]
ss问题已修复

**Comment by handbye** [comment]
已更新，但是问题依旧。 我加你QQ没收到吗，要不你加我吧。我qq:1010377293

**Comment by MikoyChinese** [comment]
无法获取订阅信息，订阅站点访问失败。
也是Https，但是我用requests.get()能返回正确且200,base64解析也没问题。
但软件就是添加不了订阅。

**Comment by cailong-1** [comment]
我也遇到标题的问题，无法添加成功，获取不了订阅，https

**Comment by lehug** [comment]
同样问题
