### ISSUE TITLE
为什么安装到最后报错？谢谢

### ISSUE THREAD

**Issue by appleyuchi** [jiangxufeng/v2rayL#69]
root@ubuntu:V2Ray# bash <(curl -s -L http://dl.thinker.ink/install.sh)
创建   /etc/v2rayL
已存在/etc/v2rayL
创建   /usr/bin/v2rayL
已存在/usr/bin/v2rayL
正在下载内核文件
--2019-11-24 23:08:40--  https://development4.baidupan.com/112423bb/2019/11/24/facda1c279d32d879f1ba0ba098fe378.tar?st=KjcRrySRjgKwA0bUdgpAHw&e=1574610120&b=VnIBMwl7UzdWegR_aBTYCaQMkCDEALwZ0BzVfIA_c_c&fi=14416724&up=
正在查找主機 development4.baidupan.com (development4.baidupan.com)... 122.226.181.186
正在連接 development4.baidupan.com (development4.baidupan.com)|122.226.181.186|:443... 連上了。
已送出 HTTP 要求，正在等候回應... 200 OK
長度: 33310720 (32M) [application/octet-stream]
Saving to: ‘/etc/v2rayL/v2ray-core.tar’

/etc/v2rayL/v2ray-c 100%[===================>]  31.77M  6.85MB/s    in 4.9s    

2019-11-24 23:08:45 (6.44 MB/s) - ‘/etc/v2rayL/v2ray-core.tar’ saved [33310720/33310720]

正在下载service文件
判断静态文件夹是否存在  /etc/v2rayL/images
已存在/etc/v2rayL/images
rm: 無法移除 '/etc/v2rayL/images-v2.0.2.tar': 沒有此一檔案或目錄
正在下载v2rayLui
--2019-11-24 23:08:46--  https://development0.baidupan.com/112423bb/2019/11/24/e51609332c7714e1e75c9ffa68b17048.tar?st=rdszMqdF04d4ZB8NxIBZ_w&e=1574610126&b=UnZdbwh6UzdYdAcdACUHalUuDycEZFAk&fi=14417691&up=
正在查找主機 development0.baidupan.com (development0.baidupan.com)... 122.226.181.178
正在連接 development0.baidupan.com (development0.baidupan.com)|122.226.181.178|:443... 連上了。
已送出 HTTP 要求，正在等候回應... 200 OK
長度: 68597760 (65M) [application/octet-stream]
Saving to: ‘/usr/bin/v2rayL/v2rayLui.tar’

/usr/bin/v2rayL/v2r 100%[===================>]  65.42M  5.47MB/s    in 11s     

2019-11-24 23:08:57 (5.81 MB/s) - ‘/usr/bin/v2rayL/v2rayLui.tar’ saved [68597760/68597760]

下载依赖文件
正在讀取套件清單... 完成
正在重建相依關係          
正在讀取狀態資料... 完成
zbar-tools 已是最新版本 (0.10+doc-10.1build3)。
以下套件為自動安裝，並且已經無用：
  at attr avahi-utils cheese-common command-not-found-data cppcheck
  cups-pk-helper dc dctrl-tools debian-archive-keyring dkms gir1.2-atspi-2.0
  gir1.2-cheese-3.0 gir1.2-clutter-1.0 gir1.2-cogl-1.0 gir1.2-coglpango-1.0
  gir1.2-ggit-1.0 gir1.2-goa-1.0 gir1.2-gst-plugins-base-1.0
  gir1.2-gstreamer-1.0 gir1.2-gtk-2.0 gir1.2-gtkclutter-1.0
  gir1.2-gucharmap-2.90 gir1.2-json-1.0 gir1.2-notify-0.7 gir1.2-polkit-1.0
  gir1.2-secret-1 gir1.2-snapd-1 gir1.2-wnck-3.0 gnome-software-common
  ibverbs-providers ippusbxd libacl1-dev libattr1-dev
  libb-hooks-endofscope-perl libb-hooks-op-check-perl libboost-system1.65.1
  libboost-thread1.65.1 libcairo-script-interpreter2 libcap-dev libcheese8
  libclass-method-modifiers-perl libclass-xsaccessor-perl libclutter-1.0-0
  libclutter-1.0-common libclutter-gst-3.0-0 libclutter-gtk-1.0-0
  libcogl-common libcogl-pango20 libcogl-path20 libcogl20 libdata-optlist-perl
  libdbus-1-dev libdevel-callchecker-perl libdevel-globaldestruction-perl
  libdevmapper-event1.02.1 libdistro-info-perl libdrm-dev
  libdynaloader-functions-perl libegl1-mesa-dev libepoxy-dev libffi-dev
  libfile-chdir-perl libfile-homedir-perl libfile-which-perl
  libfontconfig1-dev libfreetype6-dev libfribidi-dev
  libgetopt-long-descriptive-perl libgit-wrapper-perl libgit2-27
  libgit2-glib-1.0-0 libgl1-mesa-dev libgles1 libgloox17 libglvnd-core-dev
  libglvnd-dev libgo13 libgoogle-perftools4 libgsoap-2.8.60 libhttp-parser2.8
  libibverbs1 libimport-into-perl liblist-compare-perl liblvm2app2.2
  libmatheval1 libmbedcrypto1 libmbedtls10 libmbedx509-0
  libmodule-implementation-perl libmodule-runtime-perl libmongoclient0
  libmonosgen-2.0-1 libmoo-perl libnamespace-clean-perl libnl-route-3-200
  libnumber-compare-perl libnumber-range-perl libopengl0 libpackage-stash-perl
  libpackage-stash-xs-perl libparams-classify-perl libparams-util-perl
  libparams-validate-perl libpath-iterator-rule-perl libpath-tiny-perl
  libphp-embed libphp7.2-embed libpixman-1-dev libpod-constants-perl libpq5
  librados2 librdmacm1 libreadline5 libregexp-pattern-license-perl
  librole-tiny-perl libsane-hpaio libsigc++-2.0-dev libsort-key-perl
  libsort-versions-perl libstrictures-perl libstring-copyright-perl
  libstring-escape-perl libstring-shellquote-perl libsub-exporter-perl
  libsub-exporter-progressive-perl libsub-identify-perl libsub-install-perl
  libsub-quote-perl libtcmalloc-minimal4 libtext-glob-perl libtinyxml2-6a
  libunicode-utf8-perl liburcu6 libv8-3.14.5 libvariable-magic-perl
  libvncserver1 libwayland-bin libwayland-dev libx11-xcb-dev libxcb-dri2-0-dev
  libxcb-dri3-dev libxcb-glx0-dev libxcb-present-dev libxcb-randr0-dev
  libxcb-render0-dev libxcb-shape0-dev libxcb-shm0-dev libxcb-sync-dev
  libxcb-xfixes0-dev libxcomposite-dev libxcursor-dev libxdamage-dev
  libxext-dev libxfixes-dev libxft-dev libxi-dev libxinerama-dev
  libxkbcommon-dev libxml++2.6-2v5 libxrandr-dev libxrender-dev
  libxshmfence-dev libxtst-dev libxxf86vm-dev libyaml-cpp0.5v5 licensecheck
  linux-headers-4.18.0-10 linux-headers-4.18.0-10-generic
  linux-image-4.18.0-10-generic linux-modules-4.18.0-10-generic
  linux-modules-extra-4.18.0-10-generic mesa-common-dev mongo-tools
  mongodb-clients mongodb-server mongodb-server-core mscompress php-common
  php7.2-cli php7.2-common php7.2-json php7.2-opcache php7.2-readline
  pulseaudio-module-bluetooth python-certifi python-chardet
  python-concurrent.futures python-defusedxml python-gevent python-greenlet
  python-jwt python-prettytable python-requests python-soappy python-trollius
  python-urllib3 python-wstools python3-pygments session-migration sgt-puzzles
  sqlite3 squashfs-tools uuid-dev virtualbox-dkms wayland-protocols
  x11proto-composite-dev x11proto-damage-dev x11proto-fixes-dev
  x11proto-randr-dev x11proto-record-dev x11proto-xext-dev
  x11proto-xf86vidmode-dev x11proto-xinerama-dev
使用 'sudo apt autoremove' 將之移除。
升級 0 個，新安裝 0 個，移除 0 個，有 1 個未被升級。
设置桌面图标
--2019-11-24 23:08:58--  http://cloud.thinker.ink/download/v2rayL.desktop
正在查找主機 cloud.thinker.ink (cloud.thinker.ink)... 61.184.215.223
正在連接 cloud.thinker.ink (cloud.thinker.ink)|61.184.215.223|:80... 連上了。
已送出 HTTP 要求，正在等候回應... 200 OK
長度: 158 [application/x-desktop]
Saving to: ‘/usr/share/applications/v2rayL.desktop.1’

v2rayL.desktop.1    100%[===================>]     158  --.-KB/s    in 0s      

2019-11-24 23:08:58 (22.6 MB/s) - ‘/usr/share/applications/v2rayL.desktop.1’ saved [158/158]

root ALL=NOPASSWD:/bin/systemctl restart v2rayL.service,/bin/systemctl start v2rayL.service,/bin/systemctl stop v2rayL.service,/bin/systemctl status v2rayL.service,/bin/systemctl enable v2rayL.service,/bin/systemctl disable v2rayL.service,/bin/bash /etc/v2rayL/add.sh,/bin/bash /etc/v2rayL/remove.sh
安装完成.
root@ubuntu:V2Ray# Traceback (most recent call last):
  File "utils.py", line 74, in qt_message_handler
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by jiangxufeng** [comment]
你好，这是因为权限问题导致的，你可以看一下[#53 ](https://github.com/jiangxufeng/v2rayL/issues/53)
