### ISSUE TITLE
版本更新后，版本说明未修改版本号，老铁

### ISSUE THREAD

**Issue by liulei92** [jiangxufeng/v2rayL#8]
[http://ww1.sinaimg.cn/large/8afa78b7ly1g6u5ctqzwoj20m70gfdle.jpg](http://ww1.sinaimg.cn/large/8afa78b7ly1g6u5ctqzwoj20m70gfdle.jpg)

老铁，版本号 忘记修改了；还有文字显示不全

**Comment by jiangxufeng** [comment]
因为一些事情，昨天在改的时候有点心不在焉，确实考虑不周，谢谢指出

**Comment by liulei92** [comment]
小问题
