### ISSUE TITLE
下载了v2ray和v2rayL,测试当前延时没问题，但是chrome就是翻不了墙

### ISSUE THREAD

**Issue by hznuksco** [jiangxufeng/v2rayL#89]
![2019-12-08 17-00-47屏幕截图](https://user-images.githubusercontent.com/27288263/70387146-55ba6580-19dc-11ea-9bd4-d2c90a4fe507.png)

**Comment by hznuksco** [comment]
![2019-12-08 17-00-47屏幕截图](https://user-images.githubusercontent.com/27288263/70387154-6bc82600-19dc-11ea-9d13-b82068d02219.png)

**Comment by hznuksco** [comment]
莫名其妙可以了，选了黑名单模式。

**Comment by jiangxufeng** [comment]
如果没使用全局代理的话，浏览器需要配置代理才可以访问google，推荐使用	
SwitchyOmega插件

**Comment by hznuksco** [comment]
> 如果没使用全局代理的话，浏览器需要配置代理才可以访问google，推荐使用
> SwitchyOmega插件

谢谢 已经ok了

**Comment by SU-HI9** [comment]
v2rayN在chrome浏览器和edge浏览器开始都能用，今天发现所有节点测试显示无法连接，chrome无法使用edge可以使用单响应慢，重置v2rayN路由后浏览器恢复正常，节点依然显示无法连接。
![Uploading 屏幕截图 2021-02-03 194917.png…]()
