### ISSUE TITLE
选择保存地址后 打开的文件保存弹窗有点怪

### ISSUE THREAD

**Issue by liulei92** [jiangxufeng/v2rayL#9]
[http://ww1.sinaimg.cn/large/8afa78b7ly1g6u5ek4d6gj219c0ljwmt.jpg](http://ww1.sinaimg.cn/large/8afa78b7ly1g6u5ek4d6gj219c0ljwmt.jpg)

`
这个保存操作，咋用？没搞明白有点
`

**Comment by jiangxufeng** [comment]
因为是要导出一个json文件，在不同用户的主机上，USER用户名不一致，因此我设定的初始目录是/home，然后用户选择一个需要保存的目录，填写保存文件名后就可以导出

**Comment by liulei92** [comment]
1.Ubuntu 16.04  需要先创建一个json文件，然后选中 才可以导出
2.到处的配置中 好像不怎么全，不包含可用列表中所有的vmess 链接
