### ISSUE TITLE
提议：获取订阅时附加上User-Agent

### ISSUE THREAD

**Issue by ix64** [jiangxufeng/v2rayL#97]
希望获取订阅时发送包含客户端版本信息的User-Agent，不知道大家的意向如何

**Comment by RebornL** [comment]
这个功能是为啥？有什么作用？

**Comment by ix64** [comment]
我的想法是：服务器可以对Uaer-Agent来进行判断，是否返回订阅内容

**Comment by RebornL** [comment]
这个功能感觉很小众，因为买的订阅一般都能够给电脑，手机端返回。除非自建服务器，有这个功能需求。这个功能挺容易实现的

**Comment by RebornL** [comment]
不过，由于User-Agent可以伪造，所以实际上无法真正判断客户端是移动端还是PC端

**Comment by ix64** [comment]
我写个PR吧，就是不确定大家是否接受

**Comment by ix64** [comment]
> 不过，由于User-Agent可以伪造，所以实际上无法真正判断客户端是移动端还是PC端

只要能把浏览器访问和客户端访问大致区分就好了，有人要伪造成本也高一点

**Comment by ix64** [comment]
预防订阅链接在微信之类的工具传播时，几乎算是明文的信息被读取

**Comment by ix64** [comment]
#105 已实现
