### ISSUE TITLE
树莓派下一键安装提示错误

### ISSUE THREAD

**Issue by Spyderco1977** [jiangxufeng/v2rayL#99]
树莓派下一键安装提示错误
pi@raspberrypi:~$ /dev/fd/63:行64: /usr/bin/v2rayL/v2rayLui：无法执行二进制文件: 可执行文件格式错误

请问是什么原因，有无解决办法，谢谢！

**Comment by SkTsKtSkT1** [comment]
请问你问题解决了吗

**Comment by Spyderco1977** [comment]
如果不会自己编译，寻找并更换现成的固件才是明智选择。
